### ISSUE TITLE
Compiling Issue

### ISSUE THREAD

**Issue by lloyd094** [hang-up/buuk#27]
I recently gave 3.1 a go, and migrated my files to the new structure. Unfortunately I've run into this issue on both systems I've tested it on (Arch Linux, Windows 10):
```
<% for (var chunk of webpack.chunks) { for (var file of chunk.files) { if (file.match(/\.(js|css)$/)) { %> <% }}} %> 

<%= htmlWebpackPlugin.options.serviceWorkerLoader %> 
```
I'm not really sure what's caused these - the Linux build seemed to work alright, with the exception of saying there was an error with latex:
```java
ERROR in static/js/vendor.d247c2fdfc39c55d0f9e.js from UglifyJs
Unexpected token: operator (>) [./~/markdown-it-latex/src/index.js:6,0][static/js/vendor.d247c2fdfc39c55d0f9e.js:64080,26]
```
The windows build however had many more blatant issues:
```java
ERROR in ./~/fuse.js/dist/fuse.js
Module build failed: ReferenceError: Unknown plugin "babel-plugin-add-module-exports" specified in "C:\\xampp\\htdocs\\buk\\node_modules\\fuse.js\\.babelrc" at 0, attempted to resolve relative to "C:\\xampp\\htdocs\\buk\\node_modules\\fuse.js"
    at C:\xampp\htdocs\buk\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (C:\xampp\htdocs\buk\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (C:\xampp\htdocs\buk\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
    at OptionManager.init (C:\xampp\htdocs\buk\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\xampp\htdocs\buk\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\xampp\htdocs\buk\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\xampp\htdocs\buk\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\xampp\htdocs\buk\node_modules\babel-loader\lib\index.js:46:20)
    at Object.module.exports (C:\xampp\htdocs\buk\node_modules\babel-loader\lib\index.js:163:20)
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/js/components/search/search.vue 71:0-27
 @ ./src/js/components/search/search.vue
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/js/components/sidebar/sidebar.vue
 @ ./src/js/components/sidebar/sidebar.vue
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue
 @ ./src/App.vue
 @ ./src/main.js

ERROR in   Error: C:\xampp\htdocs\buk\index.html:11328
  $export($export.S + $export.F * !__webpack_require__(1), 'Object', { defineProperty: __webpa  ck_require__(6).f });
  ^
  TypeError: $export is not a function

  - index.html:11328 Object.<anonymous>
    C:/xampp/htdocs/buk/index.html:11328:1

  - index.html:21 __webpack_require__
    C:/xampp/htdocs/buk/index.html:21:30

  - index.html:10898 Object.<anonymous>
    C:/xampp/htdocs/buk/index.html:10898:1

  - index.html:21 __webpack_require__
    C:/xampp/htdocs/buk/index.html:21:30

  - index.html:10791 Object.<anonymous>
    C:/xampp/htdocs/buk/index.html:10791:31

  - index.html:21 __webpack_require__
    C:/xampp/htdocs/buk/index.html:21:30

  - index.html:179 Object.<anonymous>
    C:/xampp/htdocs/buk/index.html:179:23

  - index.html:21 __webpack_require__
    C:/xampp/htdocs/buk/index.html:21:30

  - index.html:281 Object.<anonymous>
    C:/xampp/htdocs/buk/index.html:281:10

  - index.html:21 __webpack_require__
    C:/xampp/htdocs/buk/index.html:21:30



  Build complete.
```

Any clue as to what's going on? As stated at the beginning, I get the same result regardless if I run via Linux or Windows. Thanks!

**Comment by hang-up** [comment]
Seems like you are missing a few packages? Did you `npm install` after pulling the new changes? 

On a sidenotre, you won't be able to open `index.html` in your browser since it has webpack-specific snippets of code allowing to load the right script chunks. Only outputted files available inside `/dist` should be opened in a browser ;)

**Comment by lloyd094** [comment]
I have done `npm install` a few times (just to make sure errors didn't get in the way). Still doesn't work.

Just to make sure I was getting the right `index.html`, I copied the `/dist` folder to `/htdocs` in XAMPP and got the following error:

```java
HtmlWebpack Plugin: 
  Error: C:\xampp\htdocs\buk\index.html:11328
  $export($export.S + $export.F * !__webpack_require__(1), 'Object', { defineProperty: __webpa  ck_require__(6).f });
  ^
  TypeError: $export is not a function
  
  - index.html:11328 Object.
    C:/xampp/htdocs/buk/index.html:11328:1
  
  - index.html:21 __webpack_require__
    C:/xampp/htdocs/buk/index.html:21:30
  
  - index.html:10898 Object.
    C:/xampp/htdocs/buk/index.html:10898:1
  
  - index.html:21 __webpack_require__
    C:/xampp/htdocs/buk/index.html:21:30
  
  - index.html:10791 Object.
    C:/xampp/htdocs/buk/index.html:10791:31
  
  - index.html:21 __webpack_require__
    C:/xampp/htdocs/buk/index.html:21:30
  
  - index.html:179 Object.
    C:/xampp/htdocs/buk/index.html:179:23
  
  - index.html:21 __webpack_require__
    C:/xampp/htdocs/buk/index.html:21:30
  
  - index.html:281 Object.
    C:/xampp/htdocs/buk/index.html:281:10
  
  - index.html:21 __webpack_require__
    C:/xampp/htdocs/buk/index.html:21:30
```
Did I do a step wrong?

**Comment by hang-up** [comment]
Hmm can you copy/paste the content of your `index.html` here?

**Comment by lloyd094** [comment]
`index.html` from the base folder (same for both Windows and Linux compiled) is as follows:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bük</title>
    <link rel="icon" type="image/png" sizes="32x32" href="/static/img/icons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/static/img/icons/favicon-16x16.png">
    <!--[if IE]><link rel="shortcut icon" href="/static/img/icons/favicon.ico"><![endif]-->

    <!-- Add to home screen for Android and modern mobile browsers -->
    <link rel="manifest" href="/static/manifest.json">
    <meta name="theme-color" content="#fff">

    <!-- Add to home screen for Safari on iOS -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="buuk">
    <link rel="apple-touch-icon" sizes="180x180" href="/static/img/icons/apple-touch-icon.png">
    <link rel="mask-icon" href="/static/img/icons/safari-pinned-tab.svg" color="#d95959">


    <!-- Add to home screen for Windows -->
    <meta name="msapplication-config" content="/static/img/icons/browserconfig.xml">

    <% for (var chunk of webpack.chunks) {
        for (var file of chunk.files) {
          if (file.match(/\.(js|css)$/)) { %>
    <link rel="<%= chunk.initial?'preload':'prefetch' %>" href="<%= htmlWebpackPlugin.files.publicPath + file %>" as="<%= file.match(/\.css$/)?'style':'script' %>"><% }}} %>

    <!-- BÜK: specific style -->
    <!--<link rel="stylesheet" href="dist/mermaid.min.css">-->

  </head>
  <body>
    <noscript>
      You will need Javascript enabled in order to use this app.
    </noscript>
    <div id="app"></div>

    <!-- BÜK: specific scripts -->
    <!--<script src="dist/mermaid.min.js"></script>-->

    <%= htmlWebpackPlugin.options.serviceWorkerLoader %>
    <!-- built files will be auto injected -->
  </body>
</html>
```
The Windows compilation of `dist/index.html` is as follows:
```js
Html Webpack Plugin:
<pre>
  Error: C:\xampp\htdocs\buk\index.html:11328
  $export($export.S + $export.F * !__webpack_require__(1), 'Object', { defineProperty: __webpa  ck_require__(6).f });
  ^
  TypeError: $export is not a function
  
  - index.html:11328 Object.<anonymous>
    C:/xampp/htdocs/buk/index.html:11328:1
  
  - index.html:21 __webpack_require__
    C:/xampp/htdocs/buk/index.html:21:30
  
  - index.html:10898 Object.<anonymous>
    C:/xampp/htdocs/buk/index.html:10898:1
  
  - index.html:21 __webpack_require__
    C:/xampp/htdocs/buk/index.html:21:30
  
  - index.html:10791 Object.<anonymous>
    C:/xampp/htdocs/buk/index.html:10791:31
  
  - index.html:21 __webpack_require__
    C:/xampp/htdocs/buk/index.html:21:30
  
  - index.html:179 Object.<anonymous>
    C:/xampp/htdocs/buk/index.html:179:23
  
  - index.html:21 __webpack_require__
    C:/xampp/htdocs/buk/index.html:21:30
  
  - index.html:281 Object.<anonymous>
    C:/xampp/htdocs/buk/index.html:281:10
  
  - index.html:21 __webpack_require__
    C:/xampp/htdocs/buk/index.html:21:30
  
</pre>
```
The Linux compilation of `dist/index.html` results in a blank screen with no errors, and is as follows:
```js
<!DOCTYPE html><html lang=en><head><meta charset=utf-8><meta http-equiv=X-UA-Compatible content="IE=edge"><meta name=viewport content="width=device-width,initial-scale=1"><title>Bük</title><link rel=icon type=image/png sizes=32x32 href=/static/img/icons/favicon-32x32.png><link rel=icon type=image/png sizes=16x16 href=/static/img/icons/favicon-16x16.png><!--[if IE]><link rel="shortcut icon" href="/static/img/icons/favicon.ico"><![endif]--><link rel=manifest href=/static/manifest.json><meta name=theme-color content=#fff><meta name=apple-mobile-web-app-capable content=yes><meta name=apple-mobile-web-app-status-bar-style content=black><meta name=apple-mobile-web-app-title content=buuk><link rel=apple-touch-icon sizes=180x180 href=/static/img/icons/apple-touch-icon.png><link rel=mask-icon href=/static/img/icons/safari-pinned-tab.svg color=#d95959><meta name=msapplication-config content=/static/img/icons/browserconfig.xml><link rel=preload href=/static/js/vendor.d247c2fdfc39c55d0f9e.js as=script><link rel=preload href=/static/js/app.db4bf0168934c7f6d9c0.js as=script><link rel=preload href=/static/css/app.83f55f02509ccdf1d19fc1a6baa9f78c.css as=style><link rel=preload href=/static/js/manifest.5f7fc313cd79a929386c.js as=script><link href=/static/css/app.83f55f02509ccdf1d19fc1a6baa9f78c.css rel=stylesheet></head><body><noscript>You will need Javascript enabled in order to use this app.</noscript><div id=app></div><script>(function() {
  'use strict';

  // Check to make sure service workers are supported in the current browser,
  // and that the current page is accessed from a secure origin. Using a
  // service worker from an insecure origin will trigger JS console errors.
  const isLocalhost = Boolean(window.location.hostname === 'localhost' ||
      // [::1] is the IPv6 localhost address.
      window.location.hostname === '[::1]' ||
      // 127.0.0.1/8 is considered localhost for IPv4.
      window.location.hostname.match(
        /^127(?:\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}$/
      )
    );

  window.addEventListener('load', function() {
      if ('serviceWorker' in navigator &&
          (window.location.protocol === 'https:' || isLocalhost)) {
        navigator.serviceWorker.register('service-worker.js')
        .then(function(registration) {
          // updatefound is fired if service-worker.js changes.
          registration.onupdatefound = function() {
            // updatefound is also fired the very first time the SW is installed,
            // and there's no need to prompt for a reload at that point.
            // So check here to see if the page is already controlled,
            // i.e. whether there's an existing service worker.
            if (navigator.serviceWorker.controller) {
              // The updatefound event implies that registration.installing is set
              const installingWorker = registration.installing;

              installingWorker.onstatechange = function() {
                switch (installingWorker.state) {
                  case 'installed':
                    // At this point, the old content will have been purged and the
                    // fresh content will have been added to the cache.
                    // It's the perfect time to display a "New content is
                    // available; please refresh." message in the page's interface.
                    break;

                  case 'redundant':
                    throw new Error('The installing ' +
                                    'service worker became redundant.');

                  default:
                    // Ignore
                }
              };
            }
          };
        }).catch(function(e) {
          console.error('Error during service worker registration:', e);
        });
      }
  });
})();</script><script type=text/javascript src=/static/js/manifest.5f7fc313cd79a929386c.js></script><script type=text/javascript src=/static/js/vendor.d247c2fdfc39c55d0f9e.js></script><script type=text/javascript src=/static/js/app.db4bf0168934c7f6d9c0.js></script></body></html>
```

**Comment by hang-up** [comment]
Linux compilation of `dist/index.html` seems to be alright to me. 
Just to be sure, you are not opening `dist/index.html` over `file://` right? (aka, you are not just double clicking on the file). Because if so, it won't work and will display a blank page. Built files are meant to be served over an HTTP network.
If you are serving over HTTP, are there any errors displayed in the browser console?

As for the Windows compilation of `dist/index.html` something is definitely off. After some digging, I might have found the problem: seems like windows and babel 6 transform runtime plugin don't play well with each other for some reasons. I'll try to publish a patch later on!

**Comment by lloyd094** [comment]
Correct, I am not double clicking it. I load it up via XAMPP, and it will just show a simple page with the following error:
```
<% for (var chunk of webpack.chunks) { for (var file of chunk.files) { if (file.match(/\.(js|css)$/)) { %> <% }}} %> 

<%= htmlWebpackPlugin.options.serviceWorkerLoader %> 
```
Nothing shows in the console.

Good to know about the Windows dependency issue. Will be interesting to see how it reacts comparing the current Linux rendered .html with the Windows rendered one.

**Comment by lloyd094** [comment]
Compiling issue fixed on recent update, XAMPP is the blank screen culprit!
